language: java

jdk:
    - oraclejdk8

git:
    depth: false

install:
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch origin --tags
    - git branch -a
    - git tag -l
    - git status
    - git symbolic-ref --short HEAD || git checkout $TRAVIS_BRANCH
    - git branch -a
    - git tag -l
    - git status

script:
    - "./gradlew build -i --continue"

after_success:
    - ls -al humane.gpg*
    - shasum humane.gpg*
    - openssl aes-256-cbc -K $encrypted_b0e4d3a48d05_key -iv $encrypted_b0e4d3a48d05_iv -in humane.gpg.enc -out humane.gpg -d
    - ls -al humane.gpg*
    - shasum humane.gpg*
    - "./gradlew --no-daemon --info --console=plain publish"
